# Project Eight Docker Compose (https://github.com/ProjectEight/magento2-docker-compose)
# Version 0.2.0

app:
  image: projecteight/nginx-1.11:latest
  links:
    - phpfpm
    - db
  volumes_from:
    - appdata
  ports:
    - 8000:80

appdata:
  image: tianon/true
  volumes:
#    - /var/www/html
    # Required to install M2 without username/password prompt
    # Replace the first part (before the colon) with the path to the COMPOSER_HOME folder on the host
    - /home/zone8/.composer/:/var/www/.composer/
    # Map app/code and app/design folders on host to locations in the container
#    - ./html/app/code:/var/www/html/app/code
#    - ./html/app/design:/var/www/html/app/design

phpfpm:
  image: projecteight/php7.0-fpm:latest
  links:
    - db
  volumes_from:
    - appdata

db:
  image: percona:5.7
  volumes_from:
    - dbdata
  ports:
    - 8001:3306
  env_file: env/mysql.env

dbdata:
  image: tianon/true
  volumes:
    - /var/lib/mysql

setup:
  image: projecteight/php7.0-fpm:latest
  command: /usr/local/bin/mage-setup
  links:
    - db
  volumes_from:
    - appdata
  env_file: env/setup.env
