# Project Eight Docker Compose (https://github.com/ProjectEight/magento2-docker-compose)
# Version 0.1.0

app:
  image: projecteight/nginx-1.11:latest
  links:
    - phpfpm
    - db
  volumes_from:
    - appdata
  ports:
    - 8000:80

appdata:
  image: tianon/true
  volumes:
    - /var/www/html

phpfpm:
  image: projecteight/php7.0-fpm:latest
  links:
    - db
  volumes_from:
    - appdata

db:
  image: percona:5.7
  volumes_from:
    - dbdata
  ports:
    - 8001:3306
  env_file: env/mysql.env

dbdata:
  image: tianon/true
  volumes:
    - /var/lib/mysql

setup:
  image: projecteight/php7.0-fpm:latest
  command: /usr/local/bin/mage-setup
  links:
    - db
  volumes_from:
    - appdata
  env_file: env/setup.env
